### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by HriBB** [mattecapu/dataloader-sequelize-wrapper#1]
Hey

First of all thanks for this cool package ;)

I am getting this error

```
TypeError: Cannot read property 'toString' of undefined
```

when I try to load `BelongsTo` association. Seems that `association.foreignKeyAttribute.name` is undefined [here](https://github.com/mattecapu/dataloader-sequelize-wrapper/blob/master/index.js#L92). In my case it should be `association.foreignKey`. I'm using sequelize `3.24.6` and this is how I define my model:

```
m.Location.hasMany(m.Location, {
    as: 'Locations',
    foreignKey: 'parent_id',
});
```

This works
```
if (association.associationType === 'BelongsTo') {
  /* this is probably already cached */
  primeCachePromise =
    associatedModelCache.loadMany([
      sequelizeObject[association.foreignKey]
    ]);
} else {
```

**Comment by mattecapu** [comment]
Hi, that will probably fix it.
Unfortunately, I just guessed how to use Sequelize metadata, and since it worked in my project I assumed it was correct.  
You are free to send a PR or I'll take care of it later this week. 

(thanks for the feedback 😊)
