### ISSUE TITLE
Possible to use redis as cache layer?

### ISSUE THREAD

**Issue by mtsewrs** [mattecapu/dataloader-sequelize-wrapper#7]
Wondering if you know a way use redis with this package

**Comment by mattecapu** [comment]
This package was intended specifically for dataloader. You may want to check redis-sequelize-cache, but the API is very different. 
One way to do this would be to use a Redis-backed dataloader cache. The option is straightforward to implement,  PRs are welcome

**Comment by mattecapu** [comment]
A really simple solution (and really effective) would be to allow to pass options to Dataloader. In this way, you could provide a custom Map to be used by Dataloader (for example, something [like this](https://github.com/uber-archive/cache-redis)). See https://github.com/facebook/dataloader/blob/master/src/index.js#L26

**Comment by mtsewrs** [comment]
Yes I have been looking into that but facebook seems to recommend another way https://github.com/facebook/dataloader/blob/master/examples/Redis.md

**Comment by mattecapu** [comment]
The example you linked does something different, its using a Dataloader cache in front of a Redis store. Is this what you want to do?

**Comment by mtsewrs** [comment]
Yes that is what I was trying to do

**Comment by mattecapu** [comment]
How is sequelize involved then?

**Comment by mtsewrs** [comment]
By caching the data to redis. The reason why I want to do this is scalability.

**Comment by mattecapu** [comment]
Mmh it's still not clear to me. This package caches data fetched from a SQL store, through Sequelize, in a Dataloader whose backend is, by default, an ES6 Map.  If you want to use Redis instead, then see https://github.com/mattecapu/dataloader-sequelize-wrapper/issues/7#issuecomment-299689419
